-- Create knowledge_base_modifications table
CREATE TABLE IF NOT EXISTS public.knowledge_base_modifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kb_id text, -- Mapped from question_wiki_id
    modifier text,
    modification_time timestamptz DEFAULT now(),
    
    -- Fields from knowledge_base_v1
    question_wiki_id text,
    question_type text,
    question text,
    answer text,
    answer_type text,
    if_bm25 boolean,
    similar_questions jsonb,
    error_list jsonb,
    keyword_list jsonb,
    image_urls jsonb,
    video_urls jsonb,
    file_urls jsonb,
    link_type text,
    link_url text,
    update_time timestamptz,
    product_category_name text,
    product_name text,
    change_meta jsonb
    
    -- Embedding fields (optional, if needed for history search)
    -- embedding vector(1536),
    -- bge_m3_embedding vector(1024)
);

-- Add indexes
CREATE INDEX IF NOT EXISTS idx_kb_mod_kb_id ON public.knowledge_base_modifications (kb_id);
CREATE INDEX IF NOT EXISTS idx_kb_mod_time ON public.knowledge_base_modifications (modification_time);

-- Enable RLS
ALTER TABLE public.knowledge_base_modifications ENABLE ROW LEVEL SECURITY;

-- Policy for anon (public) access
-- Allow all operations for anon (read, insert, update, delete)
CREATE POLICY "Allow all operations for anon" ON public.knowledge_base_modifications
FOR ALL USING (true) WITH CHECK (true);
